### Site Settings ###
title               : alex.cy
description         : >-
                      I usually don't encrypt my data, but when I do, I make sure its with base64. Also, I commit to master and let the customer do QA.
baseurl             : "/personal-blog"                  # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : alex10791/alex10791.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Alexandros Andreou
  image             : /assets/profile.jpg
# behance           : your_username
# dribbble          : your_username
  email             : alex10791@gmail.com
  facebook          : alex10791
# github            : alex10791
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : alex10791
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : alex10791
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  backgammon:
    output: true
    permalink: /backgammon/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "backgammon"
    values:
      layout: "post"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
